import os

TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "YOUR_BOT_TOKEN_HERE")
API_URL = os.getenv("API_URL", "http://localhost:8000")
ADMIN_ID = 1063772095
MINI_APP_URL = "https://minestudy.vercel.app"

# Constants for conversation states
(
    WAITING_MATERIA_EMOJI, WAITING_MATERIA_NOMBRE, WAITING_MATERIA_COLOR,
    WAITING_MATERIA_NOMBRE_EDIT,
    WAITING_UNIDAD_NOMBRE, WAITING_UNIDAD_NOMBRE_EDIT,
    WAITING_TEMA_NOMBRE,
    WAITING_FLASHCARD_CSV,
    WAITING_QUIZ_JSON,
    SELECT_MATERIA, SELECT_UNIDAD, SELECT_TEMA, CONFIRM_ACTION,
    WAITING_INFOGRAFIA_TITULO, WAITING_INFOGRAFIA_FOTO,
    SELECT_INFOGRAFIA,
    WAITING_PDF_TITULO, WAITING_PDF_DOC,
    SELECT_PDF,
) = range(19)
